server:
  port: 8006

spring:
  application:
    name: eureka-client

eureka:
  client:
    serviceUrl: #注册中心地址
      defaultZone: http://lwj:lwj@122.51.153.21:8001/eureka/,http://lwj:lwj@122.51.153.21:8002/eureka/,http://lwj:lwj@122.51.153.21:8003/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5 #client发送心跳给server的频率，默认30秒
    lease-expiration-duration-in-seconds: 5 #server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内没有收到下一次心跳则移除这个实例，默认90秒
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}